name: simple_water_tracker
description: "Simple app to track your plant water level."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.1+1

environment:
    sdk: ">=3.3.2 <4.0.0"

dependencies:
    camera: ^0.10.5+9
    flutter:
        sdk: flutter
    flutter_local_notifications: ^17.0.0
    flutter_localizations:
        sdk: flutter
    flutter_timezone: ^1.0.8
    json_annotation: ^4.8.1
    path: ^1.9.0
    path_provider: ^2.1.2
    permission_handler: ^11.3.1
    provider: ^6.1.2
    shared_preferences: ^2.2.2
    timezone: ^0.9.2
    uuid: ^4.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.0
    build_runner: ^2.4.9
    json_serializable: ^6.7.1

flutter:
    uses-material-design: true

    # Enable generation of localized Strings from arb files.
    generate: true

    assets:
        # Add assets from the images directory to the application.
        - assets/images/
